### ISSUE TITLE
Skills sometimes do not increase queued attributes.

### ISSUE THREAD

**Issue by Hummington** [phi-fell/carefree_leveling#1]
Sometimes, when a skill is raised, the corresponding queued attribute **does not** increase.
This picture shows Strength 56, Queued Strength +9, Blunt Weapon 42 and Acrobatics 29 (Blue underline):
![1](https://user-images.githubusercontent.com/120605065/207726673-86c2bde5-4fb5-4848-835d-2f145e76d370.png)
This picture shows Strength 57, Queued Strength +8, **Blunt Weapon 43 and Acrobatics 30.
2 Strength skills were increased but only one Queued Strength was added to the attribute pool** (Pink underline):
![2](https://user-images.githubusercontent.com/120605065/207726732-aaf9f635-28c4-4a64-aacb-e30d611ccda6.png)

**Comment by Hummington** [comment]
My bad, I thought the skillups happened on a 1:1 basis and not off the vanilla matrix.

**Comment by phi-fell** [comment]
So to make sure there's no confusion, attributes increase by 1 for every 2 relevant skill increases.

In vanilla the multipliers for attributes at level up are:
0 skill ups: x1
1-4 skill ups: x2
5-7 skill ups: x3
8-9 skill ups: x4
10+ skill ups: x5

I average that out to 2 skill ups per attribute point because if done optimally that's what you'd get - x5 per 10 skill levels

and I just saw you closed this, I'll leave this up in case it helps anyone else :)

**Comment by xu-rek** [comment]
I don't know if that's known because it's not that important, but when you're on the level up menu with 5 skill increases it still shows you'll gain x3 attribute when you'll actually only get x2. At the end of the day it doesn't matter that much, it's just a visual incoherence, but I just thought I should let you know.

**Comment by phi-fell** [comment]
@xu-rek if you're talking about the openmw (singleplayer) version, the openmw lua api doesn't seem to have a way to modify those multiplier values.  Not sure if one is planned, but yeah, that's why I included a status menu to show what you'll actually get.
