### ISSUE TITLE
The settings in the Scripts tab do not show up.

### ISSUE THREAD

**Issue by Wizardling** [phi-fell/carefree_leveling#7]
Windows 11, OpenMW 0.48.0, GOG installed Morrowind.

![Screenshot 2024-05-30 041316](https://github.com/phi-fell/carefree_leveling/assets/3980145/4d6835f2-bbbb-49c7-b0c9-40e136303562)

**Comment by phi-fell** [comment]
Are you using the 0.48 branch?  I just updated the code for 0.49 - see issue #6 - so for 0.48 you need the code from [the 0.48 branch](https://github.com/phi-fell/carefree_leveling/tree/0.48)

**Comment by Wizardling** [comment]
I used the download link on https://modding-openmw.com/mods/phis-carefree-leveling/ 
The says README.md file says: "REQUIRES OPENMW 0.48 OR HIGHER".
So I guess not? :-)

**Comment by phi-fell** [comment]
Ah, I don't have any control over that site, I'm guessing the description is cached but the link takes you to the updated repo.

[This link](https://github.com/phi-fell/carefree_leveling/tree/0.48#phis-carefree-leveling) should take you to the right place,  just download as you did before from there.

**Comment by phi-fell** [comment]
In case anyone else has this issue, I'll leave this open for now.  Also [Here's a link directly to the 0.48 zip file download](https://github.com/phi-fell/carefree_leveling/archive/refs/heads/0.48.zip) in case that's easier for anyone

**Comment by Wizardling** [comment]
Okay, all working well now, as far as I can tell without actually having gained a level :-) Cheers!

**Comment by phi-fell** [comment]
Closing this, since I think I've resolved the confusion - the 0.48 and 0.49 versions have been moved into separate folders.  I think this makes everything simpler, clearer, and should prevent confusion if people get this mod via external sites.

I'm leaving the 0.48 branch up, so that download link will keep working, but this way no one should accidentally download the 0.49 version without realizing it.

If anyone does run into any more confusion, please submit a new issue on this repo.
